### ISSUE TITLE
Setting StartType on install for Windows

### ISSUE THREAD

**Issue by imarsman** [kardianos/service#103]
In service_windows.go, the Install function sets `StartType: mgr.StartAutomatic` when calling the `winddows svc/mgr` `CreateService` function. Looking over the code, I don't think there is a way to override this. If I am correct, I submit that it would be nice to be able to override this setting to allow for manual or automatic delayed (which I don't see in `golang.org/x/sys/windows/svc/mgr`, so that could be difficult to do).

Thank-you so much for this library. I have been able to use it to write a great Windows service installer to wrap a perl application.

**Comment by rgl** [comment]
I would also like a way to set the start type.

@imarsman why aren't you using [nssm](https://nssm.cc/) instead?

**Comment by imarsman** [comment]
I'm not using nssm because I have been wanting a single binary clients can use to set things up for Windows in a very simple way. So far I have mostly gotten what I need from this library.

**Comment by st4ycool** [comment]
@imarsman so have you succeed in installing service with Automatic(Delayed) startType?
I know that if you wanna Delayed you have to place StartTypeDelayed = 1 variable in registry. Dunno how to set that start type on installation of service
