### ISSUE TITLE
upstart detection doesn't play well with busybox

### ISSUE THREAD

**Issue by jedisct1** [kardianos/service#115]
Busybox, as found on my routers, has its own version of `/sbin/init`. That doesn't read any command-line argument. So, if you run `/sbin/init --version` this restarts the whole system, which eventually ends up in a loop.

**Comment by tectiv3** [comment]
Yeah, even if it's not end up in a loop it hangs the process. This was very weird issue to debug since detection is happening in the init() in the included package.

**Comment by SteelPhase** [comment]
I'm going to try and look at this with my copy of dd-wrt tonight. `/sbin/initctl version` is an alternative method to grab the version of upstart, and i'm going to see if that reboots the server

**Comment by SteelPhase** [comment]
`/sbin/initctl --version` seems to provide the detail we need for upstart, and doesn't cause busybox to die.
