### ISSUE TITLE
Ignore Unknown instance error in stop of restart command.

### ISSUE THREAD

**Issue by bronze1man** [kardianos/service#12]
service apache2 restart can do the job like start.
But this library can not.
you have to start ,then restart.
You can not stop,restart,it will not start the process.

**Comment by kardianos** [comment]
It can. Please read the docs.

**Comment by bronze1man** [comment]
Sorry,I can not find the docs talk about Unknown instance error of restart
I have observed that it is not ignore the Unknown instance error on linux with upstart.

**Comment by kardianos** [comment]
Use either: http://godoc.org/github.com/kardianos/service#Service
or http://godoc.org/github.com/kardianos/service#Control

You must install the service first and do so as root. Control also requires root.

**Comment by bronze1man** [comment]
Here is how I come cross this bug.
```
sudo -i
install  //success
stop
restart //fail because Unknown instance error
```

but:
```
sudo -i
service apache2 stop
service apache2 restart //success
```

So I think  `Unknown instance` error should be ignored when restart.
