### ISSUE TITLE
Get current user home directory

### ISSUE THREAD

**Issue by alex-godwin** [kardianos/service#124]
Hi there, I'm having issues detecting the user that spawned the service. I would like to get the home directory, but systemd and launchd both run as root, and don't seem to have any environment variables like SUDO_USER.

Any ideas how I could accomplish this without adding a User= directive to the [Service] section?

**Comment by kardianos** [comment]
As far as I know, there is no concept in any service system. Typically services are started by the OS config on boot. so "user that spawned the service" just isn't really a thing.

**Comment by alex-godwin** [comment]
Ok, then is there any capability to add environment variables? I know systemd supports it in the file, not sure about other service managers though.

**Comment by kardianos** [comment]
If you need to configure your service, your better off creating a configuration file.

**Comment by alex-godwin** [comment]
That's my issue, I want to access the config file that the user creates in /home/<user>/.config. The goal was to have the ability to run without the service manager and without root privileges as well as through the service manager.

**Comment by kardianos** [comment]
When installing the service, pass arguments to config. Then when running it will pass those arguments.

**Comment by alex-godwin** [comment]
Ok. I think what I will end up doing is detecting if it's being run as a service and then look for a config file outside of a user directory instead. Thanks!
