### ISSUE TITLE
When I run the executable as a service the log does not write in file

### ISSUE THREAD

**Issue by marioarizaj** [kardianos/service#129]
I am using Logrus as logger. When I run the app in interactive the logger works perfectly, but when I run it as a Windows Service it does not work.

**Comment by bradrydzewski** [comment]
@marioarizaj did you end up finding a solution? I am also using logrus and am trying to figure out how to get my output. thanks!

**Comment by For-ACGN** [comment]
@bradrydzewski When you run the executable as a windows service, the current path is "%SystemRoot%\system32" (usually "C:\Windows\System32"), so you need change dirctory to the binary path.
```go
// changed path for service
if !debug {
	path, err := os.Executable()
	if err != nil {
		return err
	}
	path = strings.Replace(path, "\\", "/", -1) // windows
	err = os.Chdir(path[:strings.LastIndex(path, "/")])
	if err != nil {
		return err
	}
}
```
I add a debug flag for test.

**Comment by zhi13137665441** [comment]
You 666
