### ISSUE TITLE
Why KeepAlive is default in launchd in osx?

### ISSUE THREAD

**Issue by bronze1man** [kardianos/service#13]
http://apple.stackexchange.com/questions/159532/how-do-i-associate-a-launchd-2-plist-with-its-domain-and-service-targets

```
Apple suggest avoiding KeepAlive and RunAtLoad because the intention is to avoid ever launching a process without a guarantee of work to be done. Both keys remain and are required for many tasks.
```

Upstart in linux do the same thing too.

I think it should look like apache2 in ubuntu,the service do not care about keepalive default.

Ps: I can not find any document of this behavior.Is this behavior same across all platform?

**Comment by kardianos** [comment]
Most service managers try to keep a service alive to some degree by restarting it if it fails. This is normal behavior and to be consistent, this is on by default.
