### ISSUE TITLE
不支持最新的windows 10

### ISSUE THREAD

**Issue by zhangxianweihebei** [kardianos/service#130]
win 10显示已经安装成功  但是 找不到安装的服务，经测试 win7 正常

**Comment by kardianos** [comment]
I've got one win 10 box. I'll give a generic service test a go and see if I can reproduce.

**Comment by zhangxianweihebei** [comment]
好的  谢谢

**Comment by One2r** [comment]
我在 win 10 上安装成功

**Comment by One2r** [comment]
@zhangxianweihebei 就是照 ```service/example/simple/main.go```结构写的。

**Comment by zhangxianweihebei** [comment]
谢谢您  我在仔细排查一下 @One2r

**Comment by kardianos** [comment]
Nice job finding the problems. Thanks for the update.
