### ISSUE TITLE
How to make sure that it has been installed

### ISSUE THREAD

**Issue by zhangxianweihebei** [kardianos/service#145]
![image](https://user-images.githubusercontent.com/15844529/44630655-be223680-a993-11e8-9e59-7ed17c451f23.png)
The.String () method does not seem to satisfy.

**Comment by zhangxianweihebei** [comment]
@jmccarthy

**Comment by kardianos** [comment]
There is a new "Status()" method that will return StatusUnknown and ErrNotInstalled if not installed. You can probably use that.

**Comment by zhangxianweihebei** [comment]
谢谢
