### ISSUE TITLE
Support ChRoot for Windows?

### ISSUE THREAD

**Issue by jsearles** [kardianos/service#149]
Windows sets the current directory of a running service to System32. I think it'd be fairly simple to support the ChRoot Config property in Windows (by calling os.Chdir within the Execute or Run method maybe?).

Is that something you'd be willing to support? I can submit a PR if so.

**Comment by kardianos** [comment]
@jsearles Thanks for the suggestion.

I don't think I'd want to do this. It would be a leaky abstraction. I often read an configuration file prior to init the service config, and that would just be confusing.

**Comment by jsearles** [comment]
ok, but this leads to inconsistent behavior across platforms, forcing consumers to do an OS check to change to the expected directory. Normally i would expect the library to even out these discrepancies.

(It's surprising that Windows defaults to this directory and doesn't expose a way to configure the working directory. Looking at closed issues i can see that this behavior has caused headaches for others as well.)
