### ISSUE TITLE
Service doesn't install on Windows

### ISSUE THREAD

**Issue by VSG24** [kardianos/service#157]
I'm on Windows 7 x64 and using your simple example the app runs OK but no service is installed at all.
How does this work? Am I missing something or what?

**Comment by kardianos** [comment]
Did you try to install it? What commands did you use?

**Comment by VSG24** [comment]
I honestly don't know the proper way to install it and there isn't any documentation available.

**Comment by kardianos** [comment]
Godoc?

**Comment by VSG24** [comment]
WHAT is the install command?

**Comment by VSG24** [comment]
Got it. Here's a example on how to pass command line arguments to a go app using this library. It installs/uninstalls the service. It should be placed inside the main function.

I also [created a gist](https://gist.github.com/VSG24/069c003a10ff60d2b1343dcce75c269c) for those interested in a more complete version.

example (execute on the cmd): `myapp.exe install`

```
// read command line args
	var argsWithoutProgName = os.Args[1:]

	for _, param := range argsWithoutProgName {
		if param == "install" {
			err = s.Install()
			if err != nil {
				logger.Error(err)
			} else {
				fmt.Println("Service installed successfully.")
			}
		} else if param == "uninstall" {
			err = s.Uninstall()
			if err != nil {
				logger.Error(err)
			} else {
				fmt.Println("Service uninstalled successfully.")
			}
		}
	}
```
