### ISSUE TITLE
service install does not work on QNAP

### ISSUE THREAD

**Issue by troian** [kardianos/service#172]
`sysv` install creates only numeric suffixes for `/etc/rc<idx>.d` [link](https://github.com/kardianos/service/blob/fffe6c52ed0fd8653543bbe72432dbf6ea02f300/service_sysv_linux.go#L103)

Some distributions like QNAP has different naming
```
drwxrwxr-x    2 admin    administ      1024 May 26 11:35 rcK.d/
drwxr-xr-x    2 admin    administ      1024 Nov 21  2006 rcK_init.d/
drwxrwxr-x    2 admin    administ      3072 May 28 21:18 rcS.d/
drwxr-xr-x    2 admin    administ      1024 Nov 21  2006 rcS_init.d/
```

Is it possible to add such suffix?

**Comment by kardianos** [comment]
If there is a way to detect QNAP specifically, (and better detection for sysv), then you could even have it be a different target.

Or, you could do a detection thing in sysv itself.

**Comment by ogimenezb** [comment]
Check this: https://github.com/kardianos/service/issues/116#issuecomment-501120674

As an example...
