### ISSUE TITLE
Any further docs ?

### ISSUE THREAD

**Issue by TomMann** [kardianos/service#175]
So what are the steps post implementing the example code to implement a service on windows ?

So I have basically copied the example code and moved some of my methods so it will function. If I execute this from the command line it still works (code is now called in service.run). Yet I don't see how I make this a service because, running this doesn't create a service I can view in service manager which is basically the fundamental reason for using this.

Im sure it's me missing something any assistance would be great.

**Comment by mahummon** [comment]
Have you tried running the binary with the service flag and install arg
```
<myservice> -service install
```

**Comment by Tom-Mann** [comment]
Sorry for the slow reply, the issue is that the simple example is missing the code required to actually implement this specifically parsing command line and parsing that into the &service.Config. Once I've done that I can see the service created.
