### ISSUE TITLE
Feature request: Add logging to service configuration

### ISSUE THREAD

**Issue by jpillora** [kardianos/service#18]
I'd send a PR, though I only know launchd, http://launchd.info/ `Config` > `StandardOutPath` `StandardErrorPath`

**Comment by kardianos** [comment]
You want a way to write the stdout and stderr to a file, correct?

Out of curiosity, what's your use case? There is the Logger interface that
talks to syslog. Do you want to capture the program output?

-Daniel

**Comment by jpillora** [comment]
My mistake, I just looked into it and you're swapping from stdout to syslog when non-interactive :+1: syslog is good for me, though logging to a file might be useful, will close and this can be reopened by someone if necessary
