### ISSUE TITLE
Separate handling of Stop and Shutdown in Windows

### ISSUE THREAD

**Issue by ardias** [kardianos/service#186]
Hi,
first thanks for the code.
I'd like to have separate handling of Stop and Shutdown "ChangeRequest" in the Windows implementation. Is there any way I can hook into the ChangeRequest channel to know which command was sent (stop, shutdown)?
Or is the only way to change the code in the switch to handle those 2 separately?

https://github.com/kardianos/service/blob/master/service_windows.go#L179

Thank you

**Comment by varas** [comment]
Duplicate https://github.com/kardianos/service/issues/220
