### ISSUE TITLE
Repo for Windows service has moved?

### ISSUE THREAD

**Issue by bbalet** [kardianos/service#19]
Hi,

As Google code is closing, the following import will no more work :

	"code.google.com/p/winsvc/eventlog"
	"code.google.com/p/winsvc/mgr"
	"code.google.com/p/winsvc/svc"

Moreover winsvc package no more compile due to an error related to cgo.
There is a fork of winsvc here : https://github.com/btcsuite/winsvc

Seemed to be abandonned by its author; see: https://code.google.com/p/winsvc/issues/detail?id=13

**Comment by kardianos** [comment]
Winsvc is moving to x/sys/windows. Once it goes in I'll update the imports.

**Comment by bbalet** [comment]
Thanks for the information, I haven't code in go for more than a year. Looks like everything has changed... All my projects don't compile anymore :(

**Comment by kardianos** [comment]
Um if you wrote on go 1.x you should be ok. If you have missing
dependencies you should vendor. See github.com/kardianos/vendor .
