### ISSUE TITLE
Simple demo in Windows 10 is not showing as a service when the .exe is started

### ISSUE THREAD

**Issue by Muddz** [kardianos/service#195]
I have copied the entire simple example and created a build and an executable file `simpleServiceDemo.exe` with Goland 2019.2 

When Right clicking on `simpleServiceDemo.exe` and clicking `Run as Administrator` I can see that `simpleServiceDemo.exe` is running in the TaskManager but not showing in the Windows Services list. 

What I'm doing wrong? 

https://github.com/kardianos/service/blob/master/example/simple/main.go

**Comment by kardianos** [comment]
You need to "install" and "start" the service, not just run it.
Running it like you did will run it like a normal program, as designed.
