### ISSUE TITLE
how to set restart interval time if program exit abortly on windows platform?

### ISSUE THREAD

**Issue by qiaoms-cloud** [kardianos/service#207]
how to set restart interval time if program exit abortly on windows platform?

**Comment by joelcho** [comment]
This package wrapperd `CreateService` from [golang/sys](https://github.com/golang/sys/blob/master/windows/zsyscall_windows.go)

```
func CreateService(mgr Handle,
serviceName *uint16, 
displayName *uint16,
access uint32, 
srvType uint32, 
startType uint32, 
errCtl uint32, 
pathName *uint16, 
loadOrderGroup *uint16, 
tagId *uint32, 
dependencies *uint16, 
serviceStartName *uint16, 
password *uint16) (handle Handle, err error)
```

Maybe you can find some codes and docs in reference to `recovery`

**Comment by tc-hib** [comment]
Hello,
I think what you are looking for is [Service.SetRecoveryActions](https://godoc.org/golang.org/x/sys/windows/svc/mgr#Service.SetRecoveryActions).
You need to directly use [golang.org/x/sys/windows/svc/mgr](https://godoc.org/golang.org/x/sys/windows/svc/mgr).

Maybe this could have been defined as a JSON string in `Config.Option["RecoveryActions"]` for example.
