### ISSUE TITLE
Autostart (Start on boot) not working on Windows

### ISSUE THREAD

**Issue by joelcho** [kardianos/service#210]
### My process

1. Run the executable on cmd.exe (Administrator). All files created.
2. Delete files which created, and shut down my computer.
3. Boot and log in.
4. NO FILES CREATED AND THE SERVICE STATUS IS `STOPED`.
5. Start the service manually. All files created.

### OS
Windows 10 Professional Edition
No. 1906
Version 18363.657
Dev mode: opened

### Codes

```go
package main

import (
	"github.com/kardianos/service"
	"log"
	"os"
)

type program struct{}

func (p program) Start(s service.Service) error {
	f, _ := os.Create("C:\\Users\\Username\\demo\\Start.txt")
	if f != nil {
		_ = f.Close()
	}
	return nil
}

func (p program) Stop(s service.Service) error {
	f, _ := os.Create("C:\\Users\\Username\\demo\\Stop.txt")
	if f != nil {
		_ = f.Close()
	}
	return nil
}

func main() {
	f, _ := os.Create("C:\\Users\\Username\\demo\\main.txt")
	if f != nil {
		_ = f.Close()
	}

	cfg := service.Config{
		Name:        "GoServiceTest",
		DisplayName: "Go service demo",
		Description: "Description Description Description",
	}

	s, e := service.New(program{}, &cfg)
	if e != nil {
		log.Fatal(e)
	}

	// always fails except service not installed
	_ = s.Install()

	_ = s.Run()
}
```

**Comment by robtrooper** [comment]
I use app -service install and app -service start 
but you need flags set to accept arguments.
like
https://github.com/kardianos/service/blob/master/example/logging/main.go

I'm not sure how having Install and run as the only functions to run would allow one to stop and then uninstall again. Your code doesn't seem to allow that.
