### ISSUE TITLE
[windows] Differentiate between "stop" and "shutdown"

### ISSUE THREAD

**Issue by ardias** [kardianos/service#220]
Hi,
i need different behaviours for when a service is stopping because the we told it to stop and the system shutting down/restarting.
I had it  implemented as a new method, Shutdown, on the Interface interface. 
I don't think it's a bad way to do it but I could also see it implemented as an attribute in System (with the required get/set funcs). This would mean that it would required Service to have a reference to System so that I could interrogate it to check if the system was being shutdown. This seems a bit more work and more changes overall. 
What do you believe would be the best approach? 

I'll send you a PR with the first approach.

**Comment by varas** [comment]
I guess this should be closed as https://github.com/kardianos/service/pull/225 was merged already.
