### ISSUE TITLE
Does this development support Windows 10?

### ISSUE THREAD

**Issue by aapi-rp** [kardianos/service#249]
On the front page in the directives, it shows that this product only supports Windows XP?  I tried to use the simple example on windows 10 and it did not show up in the service menu.  I am guessing this dev does not support Windows 10, or maybe I need better instructions on how to get this thing going on Windows 10.  Please let me know.

**Comment by kardianos** [comment]
It supports Windows 10.

**Comment by kardianos** [comment]
Please note: Windows XP+
Note the "+".
