### ISSUE TITLE
Windows: The Service did not respond to the start or control request in a timely fashion

### ISSUE THREAD

**Issue by advanderveer** [kardianos/service#25]
Hey There! I'ven been using your liberary with success on OSX and Linux but my service fails to start on windows with the error "The service did not respond to the start or control request in a timely fashion". And to get the obvious out of the way my .Start() method doesn't block and starts a goroutine as shown in the examples. 

I have limited understanding of windows services but it looks like some callback from the manager takes to long to complete. How can I debug this callback and find out why it is behaving this way?

The source can be found [here](https://github.com/timeglass/glass/tree/5602f385fe07093ca7858e8f74e50ecdda2376ba/glass-daemon), the relevant files are main.go and server.go (containing my .Start() and .Run()).

**Comment by kardianos** [comment]
That sounds like the s.Run() in main.go isn't being called fast enough. Could you put some fmt.Println(time.Now()) at the start of main and right before s.Run in main?

I agree your Start method looks fine to me.

What version of windows are you running?

**Comment by advanderveer** [comment]
Further digging showed me that I made wrong assumptions about what user would run the service, apparently this caused the main func to error before s.Run() was called. Making sure this wasn't the case solved my issue.
