### ISSUE TITLE
Startup service failed in Windows10 with golang1.15.

### ISSUE THREAD

**Issue by nswdn** [kardianos/service#254]
When I called function service.Run() that I found that a channel called sigChan in github/kardianos/service/service_windows.go was blocked without os.Signal writing into channel. 

It seems like an error in golang's sdk package os/signal/signal.go?

**Comment by kardianos** [comment]
I'm going to guess that your Start method on your program blocks. The Start method may do quick, error-prone startup tasks, but then it should quickly launch a go-routine to do on-going work. Or start a ticker, or do whatever needs to be done.

So, ensure your `Start` method doesn't block for more then a second or less.

**Comment by nswdn** [comment]
Thx for your answer.
I'm sure that my program doesn't block. I also trys example/simple/main.go's code, It blocks too  when call service.Run method.

I trace the Run method's stack and find that 
`
func (ws *windowsService) Run() error {
	ws.setError(nil)
	if !interactive {
		// Return error messages from start and stop routines
		// that get executed in the Execute method.
		// Guarded with a mutex as it may run a different thread
		// (callback from windows).
		runErr := svc.Run(ws.Name, ws)
		startStopErr := ws.getError()
		if startStopErr != nil {
			return startStopErr
		}
		if runErr != nil {
			return runErr
		}
		return nil
	}
	err := ws.i.Start(ws)
	if err != nil {
		return err
	}

	sigChan := make(chan os.Signal)

	signal.Notify(sigChan, os.Interrupt)  // Notify method does not write any signal to sigChan.

	<-sigChan  // so program blocks here.

	return ws.i.Stop(ws)
}
`

It seems to a bug in package signal in golang1.15?

**Comment by nswdn** [comment]
There are some problems with the typesetting of my issue just now. I edit it several times, sorry about it.

**Comment by kardianos** [comment]
There error is not with Go or this package. The sigChan is running in "interactive" mode (not as a service), so I assume you are running directly in a terminal after building. If you want to show your code, I can take a look.

**Comment by nswdn** [comment]
I have solved this problem that registered service has startup successfully!
At first, I register the service sucessfully when I start it, there's a error ocurred 'The service did not respond in a timely fashion'.
So I want to debug it in goland's debug mod, but I debug in interactive mode so causes 

> Thx for your answer.
> I'm sure that my program doesn't block. I also trys example/simple/main.go's code, It blocks too when call service.Run method.
> 
> I trace the Run method's stack and find that
> 
> ```
> func (ws *windowsService) Run() error {
> 	ws.setError(nil)
> 	if !interactive {
> 		// Return error messages from start and stop routines
> 		// that get executed in the Execute method.
> 		// Guarded with a mutex as it may run a different thread
> 		// (callback from windows).
> 		runErr := svc.Run(ws.Name, ws)
> 		startStopErr := ws.getError()
> 		if startStopErr != nil {
> 			return startStopErr
> 		}
> 		if runErr != nil {
> 			return runErr
> 		}
> 		return nil
> 	}
> 	err := ws.i.Start(ws)
> 	if err != nil {
> 		return err
> 	}
> 
> 	sigChan := make(chan os.Signal)
> 
> 	signal.Notify(sigChan, os.Interrupt) // Notify method doesn't write any signal to sigChan
> 
> 	<-sigChan // so sigChan blocks program here
> 
> 	return ws.i.Stop(ws)
> }
> ```
> 
> It seems to a bug in package signal in golang1.15?

It's a big mistake for me.

I try my program with no block in my Start method again today, it works!
I may overlooked some details last week. Whatever thx for your patient answer!

**Comment by nswdn** [comment]
I have solved this problem that registered service has startup successfully!
At first, I register the service sucessfully when I start it, there's a error ocurred 'The service did not respond in a timely fashion'.
So I want to debug it in goland's debug mod, but I debug in interactive mode so causes 

> Thx for your answer.
> I'm sure that my program doesn't block. I also trys example/simple/main.go's code, It blocks too when call service.Run method.
> 
> I trace the Run method's stack and find that
> 
> ```
> func (ws *windowsService) Run() error {
> 	ws.setError(nil)
> 	if !interactive {
> 		// Return error messages from start and stop routines
> 		// that get executed in the Execute method.
> 		// Guarded with a mutex as it may run a different thread
> 		// (callback from windows).
> 		runErr := svc.Run(ws.Name, ws)
> 		startStopErr := ws.getError()
> 		if startStopErr != nil {
> 			return startStopErr
> 		}
> 		if runErr != nil {
> 			return runErr
> 		}
> 		return nil
> 	}
> 	err := ws.i.Start(ws)
> 	if err != nil {
> 		return err
> 	}
> 
> 	sigChan := make(chan os.Signal)
> 
> 	signal.Notify(sigChan, os.Interrupt) // Notify method doesn't write any signal to sigChan
> 
> 	<-sigChan // so sigChan blocks program here
> 
> 	return ws.i.Stop(ws)
> }
> ```
> 
> It seems to a bug in package signal in golang1.15?

It's a big mistake for me.

I try my program with no block in my Start method again today, it works!
I may overlooked some details last week. Whatever thx for your patient answer!
