### ISSUE TITLE
Service in Windows (logs and service ui)

### ISSUE THREAD

**Issue by wari** [kardianos/service#26]
Hi there, I've just tried this out and love it! Just a few questions to know if it's expected behaviour, or something to be planned in the future.

Based on `example/logging` code on Windows (after doing `-service install` and `-service start` :

1. The Control Panel >> Local Services viewer does not list out the service name.
2. `net start` on Windows command line does not list the service at all as running
3. All the logs from the log viewer listed as the service has event ID 1.

Thanks

**Comment by kardianos** [comment]
Did you run "install" as an Administrator with full Admin rights? Installing a service will indeed report it.
...
Per point (3), if you want to change the Event ID, then you need to assert the Logger that get's returned as type windowsSystem

l, err := s.Logger()
if err != nil { ... }
winlog, is := l.(WindowsLogger)
winlog.NInfo(42, "My event text")

**Comment by wari** [comment]
Thanks for the point (3) tip, which means I probably have to encapsulate/decorate the logger with something that auto-increments. 

As for install, yes, I run cmd.exe with administrator's rights, and then execute `progname -service install`, and I believe a successful install would mean that on reboot, the service will automatically start up, as well as the logs would show up properly on the event logger. The only thing is I don't see the service listed anywhere with the Services tool, or the `net start` command. I'm not familiar with Windows enough to know what is wrong. I will do more tests tomorrow. Thanks.

Tested with Windows XP and Windows 8 Pro.

**Comment by kardianos** [comment]
Look under computer management. Right click on my computer, click manage. Under config click on services. Is it set to autostart?

**Comment by wari** [comment]
The service autostarts. Which is what I'm going for, it just doesn't show itself in the services list. I'll try other examples.

**Comment by wari** [comment]
Ok the examples does show that it works somewhat.. I have to see what I did wrong with my code, I believe it's the `func init(){}` section on main screwing things up.

**Comment by wari** [comment]
Oh, I got it! My bad!

``` go
	// For example containing AAA and ZZZ:
	svcConfig := &service.Config{
		Name:        "AAA",
		DisplayName: "ZZZ",
		Description: "ABCD.",
	}
```

While I was looking for AAA, it's listed as ZZZ! Even though the Event Log specifies AAA. I thought I was going crazy!
