### ISSUE TITLE
Install LaunchAgent on mac under /Library

### ISSUE THREAD

**Issue by pieterclaerhout** [kardianos/service#27]
Currently, when you install a LaunchAgent under MacOS X, it installs it under ~/Library/LaunchAgents.

It would be handy in some cases if you could create an option to install it under /Library/LaunchAgents so  that they get loaded for all users.

**Comment by kardianos** [comment]
Don't set user service in options.

**Comment by pieterclaerhout** [comment]
No, because that turns it into a LauchDaemon. The reason I want a LaunchAgent is so that it only runs when the user logs in and it should run under the user acount of the logged in user. LaunchDaemons always run as root which I don't want.

**Comment by kardianos** [comment]
Okay. I mainly use Linux and some Windows, so OS X is request driven. If you can send me links to official documentation I could add in support.

**Comment by pieterclaerhout** [comment]
http://launchd.info

https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man8/launchd.8.html

https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html

https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man5/launchd.plist.5.html

**Comment by timothybone** [comment]
I'm attempting to pick up where this left off. @pieterclaerhout  were you able to do this?

**Comment by pieterclaerhout** [comment]
I haven't had any more time to look into this unfortunately.

**Comment by n8felton** [comment]
Tagging myself in this to take a look at it.
