### ISSUE TITLE
Broken with the last commits

### ISSUE THREAD

**Issue by hdilberovic** [kardianos/service#275]
Upon building my project I get the following error message:

# github.com/kardianos/service
..\..\..\kardianos\service\service_windows.go:247:17: undefined: windows
..\..\..\kardianos\service\service_windows.go:248:19: not enough arguments in call to ws.Config.Option.bool
        have (string)
        want (string, bool)
..\..\..\kardianos\service\service_windows.go:249:31: undefined: windows

It worked properly yesterday, so the last commit probably caused the issue.

**Comment by kardianos** [comment]
Fixed.
