### ISSUE TITLE
How to use this package?

### ISSUE THREAD

**Issue by kargirwar** [kardianos/service#279]
Guys, I would really like to use this package. But I am struggling to get started. There is 
no documentation. Say I have this code:

```
package main

import (
    "fmt"
    "net/http"
)

func main() {
    http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
        fmt.Fprintf(w, "Hello World")
    })
    http.ListenAndServe(":8080", nil)
}
```
Can I run this code as a service on any platform using this package? How exactly? Full working examples on each of the major platforms (Windows, Linux, OSX) would be truly awesome! Thanks.

**Comment by kardianos** [comment]
https://github.com/kardianos/service/tree/master/example
