### ISSUE TITLE
[Windows] Service fails to start with ERROR_SERVICE_REQUEST_TIMEOUT

### ISSUE THREAD

**Issue by lz-dc** [kardianos/service#284]
github.com/kardianos/service v1.2.0

go.sum: 
github.com/kardianos/service v1.2.0 h1:bGuZ/epo3vrt8IPC7mnKQolqFeYJb7Cs8Rk4PSOBB/g=
github.com/kardianos/service v1.2.0/go.mod h1:CIMRFEJVL+0DS1a3Nx06NaMn4Dz63Ng6O7dl0qH0zVM=
golang.org/x/sys v0.0.0-20201015000850-e3ed0017c211 h1:9UQO31fZ+0aKQOFldThf7BKPMJTiBfWycGh/u3UoO88=
golang.org/x/sys v0.0.0-20201015000850-e3ed0017c211/go.mod h1:h1NjWce9XRLGQEsW7wpKNCjG9DtNlClVuFLEZdDNbEs=

```golang
package main

import (
	"log"
	"os"
	"github.com/kardianos/service"
)
var logger service.Logger
type program struct{}

func (p *program) Start(s service.Service) error {
	logger.Info("Staring service ...")
	go p.run()
	return nil
}
func (p *program) run() {
}
func (p *program) Stop(s service.Service) error {
	logger.Info("Stopping service ...")
	return nil
}

func main() {
	if len(os.Args) != 2 {
		log.Fatal("Please provide service option [start|stop|install|uninstall]")
		return
	}

	srvArgs := make([]string, 0)
	srvDeps := make([]string, 0)
	srvOpts := make(service.KeyValue)
	var srvUser string
	
	svcConfig := &service.Config{
		Name:        "ERROR_SERVICE_REQUEST_TIMEOUT",
		DisplayName: "ERROR SERVICE REQUEST TIMEOUT",
		Description: "Replicate service error: ERROR_SERVICE_REQUEST_TIMEOUT",
		UserName:     srvUser,
		Arguments:    srvArgs,
		Dependencies: srvDeps,
		Option:       srvOpts,
	}

	prg := &program{}
	s, err := service.New(prg, svcConfig)
	if err != nil {
		log.Fatal(err)
	}

	logger, err = s.Logger(nil)
	if err != nil {
		log.Fatal(err)
	}

	err = service.Control(s, os.Args[1])
	if err != nil {
		logger.Error(err)
	}

}
```

Steps:
 1. go mod init service_time_out
 2. go mod tidy
 3. go build
 4. .\service_time_out.exe install
 5. .\service_time_out.exe start
**E: 18:23:07 Failed to start ERROR SERVICE REQUEST TIMEOUT: The service did not respond to the start or control request in a timely fashion.**

**Comment by kardianos** [comment]
Please review the example at the top of: https://pkg.go.dev/github.com/kardianos/service

You are missing s.Run, and always calling service.Control.

**Comment by lz-dc** [comment]
> 
> 
> Please review the example at the top of: https://pkg.go.dev/github.com/kardianos/service
> 
> You are missing s.Run, and always calling service.Control.

Actual application calls s.Run() if service control options are not passed and service.Control() is exposed to let user start/stop/install/uninstall without having to necessarily use platform specific commands. This was working until recently, however after dependency upgrades recently things stopped working on windows.

We shouldn't be using service.Control() directly for run? 

```golang
        logger, err = s.Logger(nil)
	if err != nil {
		log.Fatal(err)
	}

	**if len(os.Args) != 2 {
		s.Run()
		return
	}**

	err = service.Control(s, os.Args[1])
	if err != nil {
		logger.Error(err)
	}

```

For some reason adding bold portion of works even with service control option? i.e. passing start actually starts the service.

**Comment by kardianos** [comment]
No. Control talks to windows to make service changes. s.Run starts the internal service.

**Comment by lz-dc** [comment]
Thanks, then why does adding following to code doesn't throw ERROR_SERVICE_REQUEST_TIMEOUT error even if the service is started through Control? s.Run() is never called because of the check below.

```
       if len(os.Args) != 2 {
		s.Run()
		return
	}
```

**Comment by lz-dc** [comment]
This is a strange behaviour, if one un-comments the code (with s.Run()), even though it's under a condition, service control start doesn't give errors.

```golang
package main

import (
	"log"
	"os"

	"github.com/kardianos/service"
)

var logger service.Logger

type program struct{}

func (p *program) Start(s service.Service) error {
	logger.Info("Staring service ...")
	go p.run()
	return nil
}

func (p *program) run() error {
	return nil
}

func (p *program) Stop(s service.Service) error {
	logger.Info("Stopping service ...")
	return nil
}

func main() {

	srvArgs := make([]string, 0)
	srvDeps := make([]string, 0)
	srvOpts := make(service.KeyValue)
	var srvUser string

	svcConfig := &service.Config{
		Name:         "ERROR_SERVICE_REQUEST_TIMEOUT",
		DisplayName:  "ERROR SERVICE REQUEST TIMEOUT",
		Description:  "Replicate service error: ERROR_SERVICE_REQUEST_TIMEOUT",
		UserName:     srvUser,
		Arguments:    srvArgs,
		Dependencies: srvDeps,
		Option:       srvOpts,
	}

	prg := &program{}
	s, err := service.New(prg, svcConfig)
	if err != nil {
		log.Fatal(err)
	}

	logger, err = s.Logger(nil)
	if err != nil {
		log.Fatal(err)
	}

	log.Println("Number of arguments: ", len(os.Args))
	/*
		if len(os.Args) != 2 {
			s.Run()
			return
		}
	*/

	err = service.Control(s, os.Args[1])
	if err != nil {
		logger.Error(err)
	}

}

```

**Comment by top4music** [comment]
same here, almost same code (in mine there's no service.Logger and only Name, DisplayName, Description configurations), same error

**Comment by lz-dc** [comment]
> 
> 
> same here, almost same code (in mine there's no service.Logger and only Name, DisplayName, Description configurations), same error

Thanks for the confirmation, I was pulling my hair out. 
 This is same as https://github.com/kardianos/service/tree/master/example/stopPause with s.Run() commented out.

**Comment by top4music** [comment]
and at the same time, if I want to start the service from services.msc, the error is 1053, with the same description

Something is going wrong. 
Could it be a permissions issue? My account is the administrator and I'm using an rsrc manifest to run as an administrator too.

If this library doesn't work it's a tragedy

**Comment by kardianos** [comment]
Why.... are you not simply calling s.Run? Ignore Control. just use s.Run. Also check for errors.

**Comment by top4music** [comment]
Thanks kardianos. 

Ok, with s.Run only it works. And this is undisputed.
Our goal is install and then (in the future) run service. 

for instance, my service check if an exe is running. If not, it starts it.
But for testing i use
`
func (p *program) run() error {
	return nil
}
`

**Comment by lz-dc** [comment]
> 
> 
> Why.... are you not simply calling s.Run? Ignore Control. just use s.Run. Also check for errors.

The reason being that the application binary is being used for service creation, start since the service manager commands vary across various different platforms.

**Comment by kardianos** [comment]
I would suggest to use the flag package rather then using os.Args.

**Comment by lz-dc** [comment]
> 
> I would suggest to use the flag package rather then using os.Args.
> […](#)

Yes, actual application is indeed using flag package, this was for the sample program.

**Comment by SeanGaluzzi** [comment]
we have the same issue, can't really understand why, running the program works perfectly but when we install and start the service it crashes.

Start dosen't block and has a strange behaviour:

if we omit this piece of code (which teoretically shouldn't even run)
the process completely stops to work
```golang
err = s.Run()
if err != nil {
	configs.SimpleErrorHandling(err)
}
```

that piece of code is pasted just after this:
```golang
if len(os.Args) > 1 {
	err := service.Control(s, os.Args[1])
	if err != nil {
		fmt.Println(service.ControlAction)
		configs.SimpleErrorHandling(err)
	}
	return
}
```

to run our go application:
```ps1
go build .
exec.exe install
exec.exe start
```
