### ISSUE TITLE
GITHUB dependabot "high" priority warnings

### ISSUE THREAD

**Issue by mpetavy** [kardianos/service#348]
Hi, 
there is still this CVE entry active and we get regular GITHUB warnings about using the correctly working 1.2.1 version.
Sample: (https://github.com/mpetavy/netio/security/dependabot/2)
Blackduck and others are still reporting this as a "high security risk".
After months it is fair to say that there is absoluty no progress to revoke this wrong CVE.
Can you please update to a new tag release that we can get rif of this?
Thanks in advance.
Marcel

**Comment by kardianos** [comment]
Without knowing what this CVE is (link is dead), I can't do much about it.
