### ISSUE TITLE
double quotes in ExecPath for systemd service config file breaks start command

### ISSUE THREAD

**Issue by alfintatorkace** [kardianos/service#36]
On CentOS 7, when the service config file gets written, the field value for ExecPath ends up quoted with double quotes.  Printing out my strings before calling the service start looks like there are no double quotes embedded in the string.

/etc/systemd/system/myservice.service looks like:

...
[Service]
ExecPath="/path/to/my/service/myservice"
...

When I try to start, I get:

Failed to issue method call: Unit myservice.service failed to load: Invalid argument. See system logs and 'systemctl status myservice.service' for details.

If I remove the double quotes, disable and reenable the service, it will start fine.

Is there any way to get this field written without the quotes?

thanks
alf

**Comment by kardianos** [comment]
What version of systemd are you running? Can you give me the exact name of the path it was throwing up on?

**Comment by alfintatorkace** [comment]
$ systemctl --version
systemd 208
+PAM +LIBWRAP +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ

# service wrapper generated myservice.service looks like this:

[Unit]
Description=Manages my service.
ConditionFileIsExecutable="/opt/myservice/bin/myservice"

[Service]
StartLimitInterval=5
StartLimitBurst=10
ExecStart="/opt/myservice/bin/myservice"



Restart=always
RestartSec=120

[Install]
WantedBy=multi-user.target


# Manual service commands to reproduce:

$ sudo systemctl enable myservice.service
ln -s '/etc/systemd/system/myservice.service'  '/etc/systemd/system/multi-user.target.wants/myservice.service'

$ sudo systemctl start myservice.service
Failed to issue method call: Unit myservice.service failed to load: Invalid argument. See system logs and 'systemctl status myservice.service' for details.

If I remove the quotes in the value of ExecStart, disable, enable, then start it works fine.

**Comment by alfintatorkace** [comment]
From my perspective, this has been fixed in rev d97d87340b4a0d418f4d266ca7b00ba1d31e0d5a
I tried the latest on the redhat system that was having the issue and the quotes are no longer there.
