### ISSUE TITLE
Windows service get user home is error ？

### ISSUE THREAD

**Issue by lnsane** [kardianos/service#381]
user get user home  C:\Users\admin

service get user home  C:\WINDOWS\system32\config\systemprofile

why？

**Comment by solodyagin** [comment]
Everything is correct. The service is registered and running under the system user SYSTEM.

**Comment by solodyagin** [comment]
I'm not sure, but maybe it will work

```
options := make(service.KeyValue)
options["Password"] = "Pa$$WoRd"

svcConfig := &service.Config{
	...
	UserName: "admin",
	Option:   options,
}
```
