### ISSUE TITLE
systemd service file is created with wrong permissions

### ISSUE THREAD

**Issue by blakerouse** [kardianos/service#395]
https://github.com/kardianos/service/blob/master/service_systemd_linux.go#L153

The file should be created with `0600` not `0644`.

Exact warning that a user asked in systemd - https://github.com/systemd/systemd/issues/770

**Comment by kardianos** [comment]
According to the underlying issue, if I read it correctly, the current permissions of `0644` is the correct permission set.

**Comment by blakerouse** [comment]
You are correct, my bad. I was reading this completely wrong the error message says `world-inaccessible` I was reading that as `world-accessible`.

Thanks for the response and correction.
