### ISSUE TITLE
Start service is failed in ubuntu 10.04 version

### ISSUE THREAD

**Issue by SagarPuneria** [kardianos/service#54]
I tried to run service in ubuntu 15,14,12...version.In these ubuntu versions service is started successfully.
When i tried to run service in ubuntu 10.04,it is showing error when am starting service.
err = s.Install()
if err != nil {
    fmt.Println("service not Installed successfully, ErrorInfo : ",err)
}  
err = s.Start()
if err != nil {
    fmt.Println("service not Started , ErrorInfo : ",err)
}  
O/P:-
service not Started , ErrorInfo : "initctl" failed: exit status 1, initctl: Unknown job: SERVICE_NAME.

why service is not started in ubuntu 10.04 version ? and service is started successfully in above versions.
Is this "github.com/kardianos/service" package is platform dependent/independent ?

**Comment by kardianos** [comment]
I haven't ran 10.04 for a long time. If you can diagnose, we could potentially make changes. I'm hesitant to do too much to support it because for the last year it has been un-supported.

**Comment by SagarPuneria** [comment]
// The upstart script should stop with an INT or the Go runtime will terminate
// the program before the Stop handler can run.
const upstartScript = `# {{.Description}}
 {{if .DisplayName}}description    "{{.DisplayName}}"{{end}}
kill signal INT
{{if .ChRoot}}chroot {{.ChRoot}}{{end}}
{{if .WorkingDirectory}}chdir {{.WorkingDirectory}}{{end}}
start on filesystem or runlevel [2345]
stop on runlevel [!2345]
#setuid username
respawn
respawn limit 10 5
umask 022
console none
pre-start script
    test -x {{.Path}} || { stop; exit 0; }
end script
# Start
exec {{.Path}}{{range .Arguments}} {{.|cmd}}{{end}}
`
In these above upstartScript,if i comment #kill signal INT these line.it is starting service in ubuntu 10.04 version.
Is this correct to do comment at #kill signal INT,if i do comment/remove it has any severe problem with these script.
If i do comment and  it has severe problem,then is there any alternate way to solve these issue.

**Comment by kardianos** [comment]
That actually sounds really familiar. upstart has an older version which didn't recognize the kill signal INT directive, making it incompatible with older versions.

There was a reason I added the kill signal INT. I'll need to dig through some of the older issues think on bitbucket to remember them though.

**Comment by rychipman** [comment]
Just wanted to check back in on this. I recently ran into this issue as well, but with amazon linux. Since amazon linux is something that is likely to be widely used (and isn't unsupported like Ubuntu 10.04 was), could we take a look into making this backwards compatiible? Happy to help diagnose/debug as needed.

**Comment by kardianos** [comment]
Just need to remove some of the script options I bet.

**Comment by SteelPhase** [comment]
This issue should be resolved in master
