### ISSUE TITLE
ExecStart line is wrong created at using Arguments

### ISSUE THREAD

**Issue by kless** [kardianos/service#56]
When field 'Arguments' is added to 'Config', the program adds double quotes to every argument.

Looking at '/etc/systemd/system/foo.service', in field 'ExecStart':

    ExecStart=/usr/bin/food "-env dev" "-run"

instead of:

    ExecStart=/usr/bin/food -env dev -run

**Comment by kardianos** [comment]
This is in line with systemd docs. Is it not working?

Bug in your example, env and dev should be separate args.

**Comment by kless** [comment]
I tried separating args., and the result is:

   ExecStart=/usr/bin/food "-env" "" "-d"

**Comment by kless** [comment]
It is not working; to do it, the line should be

    ExecStart=/usr/bin/food -env dev -run

I changed manually the file and it works

**Comment by kless** [comment]
Sorry! You had reason.
