### ISSUE TITLE
Choosing linux flavor

### ISSUE THREAD

**Issue by inconshreveable** [kardianos/service#6]
The choice of init system on linux is currently determined as follows:

Use systemd if available.
If not, use upstart if available.
If not, use sysvinit.

sysvinit and systemd are mutually exclusive choices because they both only run as pid 1. But it's possible to have upstart installed in addition to sysvinit or systemd, and the caller may have a preference of which they would like to use.

I want different behavior. Specifically: use systemd if available. If not, use upstart. If not, then fail. sysvinit is not an acceptable service manager for me because it does not restart failed processes.

I guess, on the overall, my preference would be to modify the API as follows:

- Expose `System` as an exported variable
- Expose `RunningSystem` interface
- Modify `RunningSystem` interface to include a new method `Available() bool`
- Expose each available service system on the current platform as a variable. So for darwin, it would only be `Launchd`. But on linux, there would be `SysvInit`, `Upstart` and `Systemd`
- Remove `Platform()` and `Interactive()`. These can both now be accessed via `System.String()` and `System.Interactive()`, respectively.

This would allow callers to override the choice of flavor if they so desired. It would further open up the ability for `kardianos/service` to support other service-running systems like supervisord or runit, if someone wanted to add support for that in the future.

Thoughts?

**Comment by kardianos** [comment]
I used to have Interactive and String as properties of an exported System. Perhaps I should re-expose them as such. Let me think about it.

I think forcing the hand of what to use is fine. I will add config parameters to enable this, along with documentation to that effect.

**Comment by kardianos** [comment]
Please refer to:
https://github.com/kardianos/service/commit/c880387deadce0245b11b9aaa0638513a1c5a6ec

I'm playing with your idea. I'm not sure if it will fly or not. I think Interactive will need to stay at a package level, but it's behavior might be modified when different systems are specified.

**Comment by kardianos** [comment]
Please review the API. I think it will now work for your use case.

**Comment by inconshreveable** [comment]
Perfect! The API is straightforward and elegant. I can throw away my hacky workaround now =) Thank you!
