### ISSUE TITLE
Config.Name must not contain spaces

### ISSUE THREAD

**Issue by jsgv** [kardianos/service#62]
Service works perfect in interactive mode, but when I try to install via `InstallUtil.exe` I get the error:

```
System.BadImageFormatException:
Could not load file or assembly 'file:///C:\Projects\Go\src\github.com\jesusjjf\myservice\main.exe' or one of its dependencies. The module was expected to contain an assembly manifest..
```

I used the [logging service example](https://github.com/kardianos/service/blob/master/example/logging/main.go)

Am I missing something? Thanks.

I am using Windows 10, but the end machine to install is a Windows Server 2012 R2

**Comment by kardianos** [comment]
That's what you use for .NET services, which have funny non-standard hooks
to setup the name, etc.

You can use the "service.Control" function internally and then run
"my-service -service install" (or similar, see examples), or you can use
sc.exe that comes with windows.

**Comment by jesusjjf** [comment]
I see. I am passing the `install` option to the `-service` flag. 
But Im still getting error `Failed to install MyServiceName: The filename, directory name, or volume label syntax is incorrect.`

Tried to set the the `Executable` path for `Service.Config{}`, but no luck.

**Comment by kardianos** [comment]
Can you show how you are configuring the service? snipit or gist? Agree, Executable isn't the issue.

**Comment by jesusjjf** [comment]
```go
package main

import (
	"flag"
	"log"
	"time"

	"github.com/jesusjjf/MyServiceName/controllers"
	"github.com/jesusjjf/MyServiceName/models"
	"github.com/kardianos/service"
)

var logger service.Logger

// Program structures.
//  Define Start and Stop methods.
type program struct {
	exit chan struct{}
}

func (p *program) Start(s service.Service) error {
	if service.Interactive() {
		logger.Info("Running in terminal.")
	} else {
		logger.Info("Running under service manager.")
	}
	p.exit = make(chan struct{})

	// Start should not block. Do the actual work async.
	go p.run()
	return nil
}

func (p *program) Stop(s service.Service) error {
	// Any work in Stop should be quick, usually a few seconds at most.
	logger.Info("I'm Stopping!")
	close(p.exit)
	return nil
}

func (p *program) run() error {
	logger.Infof("I'm running %v.", service.Platform())
	ticker := time.NewTicker(2 * time.Second)

	for {
		select {
		case tm := <-ticker.C:
			logger.Infof("Still running at %v...", tm)
			goBackup()
		case <-p.exit:
			ticker.Stop()
			return nil
		}
	}
}

// Service setup.
//   Define service config.
//   Create the service.
//   Setup the logger.
//   Handle service controls (optional).
//   Run the service.
func main() {
	// const svcName = "Backup Synchronizer"

	svcFlag := flag.String("service", "", "Control the system service.")
	flag.Parse()

	svcConfig := &service.Config{
		Name:        "Backup Synchronizer",
		DisplayName: "Backup Synchronizer",
		Description: "Syncs backups in file path to S3.",
	}

	prg := &program{}
	s, err := service.New(prg, svcConfig)
	if err != nil {
		log.Fatal(err)
	}
	errs := make(chan error, 5)
	logger, err = s.Logger(errs)
	if err != nil {
		log.Fatal(err)
	}

	go func() {
		for {
			err := <-errs
			if err != nil {
				log.Print(err)
			}
		}
	}()

	if len(*svcFlag) != 0 {
		err := service.Control(s, *svcFlag)
		if err != nil {
			log.Printf("Valid actions: %q\n", service.ControlAction)
			log.Fatal(err)
		}
		return
	}
	err = s.Run()
	if err != nil {
		logger.Error(err)
	}
}

func goBackup() {
	//.. do the work
}
```

**Comment by kardianos** [comment]
This all looks fine. 
It looks like you are getting the following error:
https://technet.microsoft.com/en-us/library/cc956689.aspx

I'm very curious to find the cause of this error. Could you instrument the following function:
https://github.com/kardianos/service/blob/master/service_windows.go#L189

See which of these errors it is failing at and the value of `exepath`?
Thanks, -Daniel

**Comment by jesusjjf** [comment]
I found that the issue was with [m.CreateService](https://github.com/kardianos/service/blob/master/service_windows.go#L205)

All the variables are set. `exepath`, `ws.name` and `mgr.Config` struct, but it returns error.

**Comment by kardianos** [comment]
Great. What was the exact value for "exepath"?

**Comment by jesusjjf** [comment]
`C:\Projects\Go\src\github.com\jesusjjf\MyServiceName\backup.exe`

No spaces, no weird characters.

**Comment by kardianos** [comment]
maybe `go get -u golang.org/x/sys/windows/svc/...` ?

Maybe restart windows?
Check for existing services with same name?
What windows version?

Sorry, I'm grasping at straws here... -Daniel

**Comment by kardianos** [comment]
What if you remove the ` ` space from "Name" field in the config?

**Comment by jesusjjf** [comment]
I was able to install it now. Now Im having different errors with the service quitting prematurely, but I dont think this is an issue with the `service` package. Thanks for the help!

**Comment by kardianos** [comment]
When creating a service, check for whitespace in name and return an error if found with better error message.
