### ISSUE TITLE
How to set Start Parameter in windows service

### ISSUE THREAD

**Issue by Vigneshr6** [kardianos/service#75]
My Application  have to get http port to run.
I have to set the port number in windows start parameter

**Comment by kardianos** [comment]
Use configuration file or pass args on install.

**Comment by Vigneshr6** [comment]
The link you gave is not valid for my account.

Can u give me the Sample code?

**Comment by Vigneshr6** [comment]
I used your logger.go program to run my go application as a service in windows.
But It did not work in linux.
Do you have any sample program for linux?

**Comment by astax-t** [comment]
Github issues is not really a place to ask for help with writing your code. They are to report problems with the product.

You might be better go and check stackoverflow.com or ask the question there.

**Comment by 2opremio** [comment]
> Use configuration file or pass args on install.

Or the library could pass the start arguments instead of ignoring them: #82  :)

> Github issues is not really a place to ask for help with writing your code. They are to report problems with the product.

I think it is the right place when the confusion is partly caused by a missing feature.

**Comment by kardianos** [comment]
To configure service to run an executable with a given set of arguments, set https://godoc.org/github.com/kardianos/service#Config.Arguments to the arguments *before install*. Then when it is started the windows service manager will pass those arguments to the executable. To access them at runtime you should use https://golang.org/pkg/os/#Args .

Please let me know if this answers your questions.

**Comment by Vigneshr6** [comment]
Yes This is what I asked?
thanks @kardianos
