### ISSUE TITLE
Windows Service runs, does not output log

### ISSUE THREAD

**Issue by imRohan** [kardianos/service#87]
Successfully installed the .exe as a service, and through service manager started it.

However, a logfile is not created in the same directory as the executable. Im not sure what im doing wrong, but if i run the executable through a command prompt the log is created and written to as intended.

```
   logFile, err := os.OpenFile("LogFile", os.O_WRONLY|os.O_CREATE|os.O_APPEND, 0644)
   if err != nil {
     log.Fatalf(err.Error())
   }

   defer logFile.Close()
   log.SetOutput(logFile)
 ...........................

   err = processService.Run()
   if err != nil {
     log.Println(err.Error())
   }

   log.Println("Service Started")

**Comment by kardianos** [comment]
The working directory for all windows services starts as C:\windows\system32 (well %SYSTEM% I think). So your file will be there.

If you want to write a file relative to your executable, you need either go1.8 os.Executable() or prior to go1.8 you will need github.com/kardianos/osext .
