### ISSUE TITLE
Is there any command line tool works with this package?

### ISSUE THREAD

**Issue by bronze1man** [kardianos/service#9]
It looks like this package can install and uninstall service.
It should be better to config it some where, and manage those service.

**Comment by kardianos** [comment]
I don't think I want to write a command line program to work with other services. Once I add the "Executable" field in Config however, you should be able to make one yourself if you so desire. I could see potentially adding such a program in the examples directory, but nothing official.

**Comment by bronze1man** [comment]
I am thinking of writing a uniform service management tool.
The native system api looks too complex for me.

**Comment by kardianos** [comment]
I won't be adding an example at this point in time. Feel free to make your own tool though.
