### ISSUE TITLE
need support for upstart (0.6.5)

### ISSUE THREAD

**Issue by Vigneshr6** [kardianos/service#96]
Hi i downloaded this library today(25-05-2017).It detects CentOS 6.6 as upstart.but it is SysV

**Comment by morfien101** [comment]
I have the same issue.

**Comment by kardianos** [comment]
I don't run CentOS. Feel free to determine why and post here.

**Comment by Vigneshr6** [comment]
ref --> https://github.com/kardianos/service/commit/a37cd5efa8d27ece7d86a6aadee4b3f590d928b3#diff-d3b10edc09138fcd64c943af2ead8df6
This additional check tells SysV as upstart in CentOS 6.6
Before this commit, it was working fine

**Comment by kardianos** [comment]
What does sbin init --version output?

**Comment by Vigneshr6** [comment]
```
init (upstart 0.6.5)
Copyright (C) 2010 Canonical Ltd.

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by kardianos** [comment]
It looks like you are running upstart. ?

**Comment by Vigneshr6** [comment]
It runs both SysV and upstart (0.6.5).
But `service serviceName start` will run only the SysV services.
`initctl start serviceName` will run upstart services.

**Comment by Vigneshr6** [comment]
Since upstart script is having `kill signal INT` ,it fails to start in centos6.

**Comment by SteelPhase** [comment]
This issue should be resolved now on master
