### ISSUE TITLE
can't connect sqlserver when run as a service

### ISSUE THREAD

**Issue by loadasp** [kardianos/service#97]
Hi,
when i run the program as console,it can connect the ms sqlserver,but when i run the program as service,it failed.
i use "github.com/mattn/go-adodb" as the db driver.i'm not sure what happened.

**Comment by kardianos** [comment]
You need to run the service as the correct user or grant the system service is is running as access to the database.

**Comment by loadasp** [comment]
Thanks,it worked

**Comment by kardianos** [comment]
Set who the service runs as manually.
