### ISSUE TITLE
Privileges issue in windows

### ISSUE THREAD

**Issue by Vigneshr6** [kardianos/service#99]
I am using this api for running my server application as a service.Now I got into a problem.I have to create a schtasks(Task Scheduler) in windows from my application.
So I executed this command from my application:
`schtasks /create /sc minute /mo 20 /tn "Test Task" /tr "C:\Program Files\myApp\scripts\run.bat"`

And it gives me this error
`No mapping between account names and security IDs was done`

But when I run my application from administrator command prompt ,It works fine.

Anyone have any idea about this?

**Comment by kardianos** [comment]
Change who the service runs as.

**Comment by Vigneshr6** [comment]
Yes,Changing service log on as to Admin user solved the issue

**Comment by ignasbernotas** [comment]
@Vigneshr6 how did you solve it? In my case I'm planning to ship the service manager binary with my software so I need it to run as admin. Is it possible to install it by "Run as Administrator" but then let normal users run it? How can I do that?
